services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: registrydb
      POSTGRES_USER: registry
      POSTGRES_PASSWORD: registrypass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    environment:
      DJANGO_SECRET_KEY: "dev-secret-key-change-me"
      DJANGO_DEBUG: "1"
      DB_NAME: registrydb
      DB_USER: registry
      DB_PASSWORD: registrypass
      DB_HOST: db
      DB_PORT: "5432"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:

